# This is a basic workflow to help you get started with Actions

name: Merge schedule

on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    - cron: "20 11 * * *"

jobs:
  merge-schedule:
    runs-on: ubuntu-latest

    steps:
      - uses: gr2m/merge-schedule-action@v1
        env: ${{ secrets.GITHUB_TOKEN }}
        with:
          time_zone: "Australia/Melbourne"
